name: jyngles
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  new_gradient_app_bar: ^0.2.0
  get: ^4.6.1
  lottie: ^1.2.2
  table_calendar: ^3.0.5
  fl_chart: ^0.50.1
  intl_phone_field: ^3.1.0
  onesignal_flutter: ^2.6.3
  checkbox_grouped: ^1.8.0
  intl_phone_number_input: ^0.7.0+2
  package_info_plus: ^1.4.2
  fluttertoast: ^8.0.9
  http: ^0.13.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  month_year_picker: ^0.1.0+2
  flutter_datetime_picker: ^1.5.1
  awesome_dialog: ^2.2.1
  circular_profile_avatar: ^2.0.0
  badges: ^2.0.2
  flutter_stripe: ^2.5.0
  plaid_flutter: ^2.2.1
  google_sign_in: ^5.3.1
  just_the_tooltip: ^0.0.11
  syncfusion_flutter_charts: ^19.4.50
  flutter_facebook_auth: ^4.3.4
  local_auth: ^2.1.0
  flutter_html: ^2.2.1
  flutter_dropdown_alert: ^1.0.4
  string_to_color: ^1.0.1
  super_tooltip: ^1.0.1
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/congrats.json
    - assets/images/splash.jpg
    - assets/images/app_icon.jpeg
